# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL-1065} -limit 10000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.cache/wt [current_project]
set_property parent.project_path D:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths d:/Project/Vivado/IP [current_project]
set_property ip_output_repo d:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/sources_1/bd/demo/hdl/demo_wrapper.v
add_files D:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/sources_1/bd/demo/demo.bd
set_property used_in_implementation false [get_files -all d:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/sources_1/bd/demo/ip/demo_processing_system7_0_0/demo_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/sources_1/bd/demo/ip/demo_rst_ps7_0_100M_0/demo_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/sources_1/bd/demo/ip/demo_rst_ps7_0_100M_0/demo_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/sources_1/bd/demo/ip/demo_rst_ps7_0_100M_0/demo_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/sources_1/bd/demo/ip/demo_axi_vdma_0_0/demo_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/sources_1/bd/demo/ip/demo_axi_vdma_0_0/demo_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/sources_1/bd/demo/ip/demo_axi_vdma_0_0/demo_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/sources_1/bd/demo/ip/demo_axi_gpio_0_0/demo_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/sources_1/bd/demo/ip/demo_axi_gpio_0_0/demo_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/sources_1/bd/demo/ip/demo_axi_gpio_0_0/demo_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/sources_1/bd/demo/ip/demo_xbar_1/demo_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/sources_1/bd/demo/ip/demo_xbar_0/demo_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/sources_1/bd/demo/ip/demo_Axis2VGA_0_0/src/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/sources_1/bd/demo/ip/demo_Axis2VGA_0_0/src/fifo_generator_0/fifo_generator_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/sources_1/bd/demo/ip/demo_OvSensor2Axis_0_0/src/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/sources_1/bd/demo/ip/demo_OvSensor2Axis_0_0/src/fifo_generator_0/fifo_generator_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/sources_1/bd/demo/ip/demo_OvSensor2Axis_0_0/src/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/sources_1/bd/demo/ip/demo_OvSensor2Axis_0_0/src/clk_wiz_0/clk_wiz_0_late.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/sources_1/bd/demo/ip/demo_OvSensor2Axis_0_0/src/clk_wiz_0/clk_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/sources_1/bd/demo/ip/demo_OvSensor2Axis_0_0/src/ovpclk.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/sources_1/bd/demo/ip/demo_clk_wiz_0_0/demo_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/sources_1/bd/demo/ip/demo_clk_wiz_0_0/demo_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/sources_1/bd/demo/ip/demo_clk_wiz_0_0/demo_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/sources_1/bd/demo/ip/demo_auto_pc_1/demo_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/sources_1/bd/demo/ip/demo_auto_pc_0/demo_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/sources_1/bd/demo/demo_ooc.xdc]
set_property is_locked true [get_files D:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/sources_1/bd/demo/demo.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/constrs_1/new/demo.xdc
set_property used_in_implementation false [get_files D:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/constrs_1/new/demo.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top demo_wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef demo_wrapper.dcp

catch { report_utilization -file demo_wrapper_utilization_synth.rpt -pb demo_wrapper_utilization_synth.pb }
