# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/demo.xdc

# Block Designs: bd/demo/demo.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==demo || ORIG_REF_NAME==demo}]

# IP: bd/demo/ip/demo_processing_system7_0_0/demo_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==demo_processing_system7_0_0 || ORIG_REF_NAME==demo_processing_system7_0_0}]

# IP: bd/demo/ip/demo_rst_ps7_0_100M_0/demo_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==demo_rst_ps7_0_100M_0 || ORIG_REF_NAME==demo_rst_ps7_0_100M_0}]

# IP: bd/demo/ip/demo_axi_vdma_0_0/demo_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==demo_axi_vdma_0_0 || ORIG_REF_NAME==demo_axi_vdma_0_0}]

# IP: bd/demo/ip/demo_axi_mem_intercon_0/demo_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==demo_axi_mem_intercon_0 || ORIG_REF_NAME==demo_axi_mem_intercon_0}]

# IP: bd/demo/ip/demo_ps7_0_axi_periph_1/demo_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==demo_ps7_0_axi_periph_1 || ORIG_REF_NAME==demo_ps7_0_axi_periph_1}]

# IP: bd/demo/ip/demo_axi_gpio_0_0/demo_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==demo_axi_gpio_0_0 || ORIG_REF_NAME==demo_axi_gpio_0_0}]

# IP: bd/demo/ip/demo_xlconcat_0_0/demo_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==demo_xlconcat_0_0 || ORIG_REF_NAME==demo_xlconcat_0_0}]

# IP: bd/demo/ip/demo_xbar_1/demo_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==demo_xbar_1 || ORIG_REF_NAME==demo_xbar_1}]

# IP: bd/demo/ip/demo_xbar_0/demo_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==demo_xbar_0 || ORIG_REF_NAME==demo_xbar_0}]

# IP: bd/demo/ip/demo_Axis2VGA_0_0/demo_Axis2VGA_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==demo_Axis2VGA_0_0 || ORIG_REF_NAME==demo_Axis2VGA_0_0}]

# IP: bd/demo/ip/demo_OvSensor2Axis_0_0/demo_OvSensor2Axis_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==demo_OvSensor2Axis_0_0 || ORIG_REF_NAME==demo_OvSensor2Axis_0_0}]

# IP: bd/demo/ip/demo_clk_wiz_0_0/demo_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==demo_clk_wiz_0_0 || ORIG_REF_NAME==demo_clk_wiz_0_0}]

# IP: bd/demo/ip/demo_auto_pc_1/demo_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==demo_auto_pc_1 || ORIG_REF_NAME==demo_auto_pc_1}]

# IP: bd/demo/ip/demo_auto_pc_0/demo_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==demo_auto_pc_0 || ORIG_REF_NAME==demo_auto_pc_0}]

# XDC: bd/demo/demo_ooc.xdc
