# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/sources_1/bd/demo/ip/demo_processing_system7_0_0/demo_processing_system7_0_0.xci
# IP: The module: 'demo_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/sources_1/bd/demo/ip/demo_processing_system7_0_0/demo_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'demo_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: D:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/sources_1/bd/demo/ip/demo_processing_system7_0_0/demo_processing_system7_0_0.xci
# IP: The module: 'demo_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Project/Vivado/Terminated_project/ZYBO_Video/ZYBO_Video.srcs/sources_1/bd/demo/ip/demo_processing_system7_0_0/demo_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'demo_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
